# Intro to Numpy

In [1]:
import numpy as np

## Array Creation

In [6]:
# create integer from list
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14],
       [ 3.14,  3.14,  3.14,  3.14,  3.14]])

In [10]:
# Create an array filled with a linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [12]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[ 0.18356523,  0.11053991,  0.20277881],
       [ 0.93156651,  0.57402787,  0.57960698],
       [ 0.97933446,  0.39445925,  0.73185012]])

In [14]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.10637784,  0.47467798, -0.25907776],
       [-0.51618028, -0.87033412, -0.80125302],
       [-0.77509677, -0.59118573,  0.11920113]])

In [15]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Indexing

In [17]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [20]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [21]:
print("dtype:", x3.dtype)

dtype: int64


In [22]:
x1[0]

5

In [23]:
x2[0, 1]

5

## UFuncs

In [24]:
x = np.arange(10)

In [25]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])